services:
  postgres:
    container_name: sportradar_postgres
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./db/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "15432:5432"
    restart: unless-stopped
    networks: 
      - sportradar
  
  pgadmin:
    container_name: sportradar_pgadmin
    image: dpage/pgadmin4:9.3
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./db/docker_pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - "15433:80"
    entrypoint:
      - /bin/sh
      - -c
      - "/bin/echo 'postgres:5432:*:postgres:password' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    restart: unless-stopped
    networks: 
      - sportradar
      
  events:
    container_name: events-service
    build: ./events
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks: 
      - sportradar
   
  frontend:
    container_name: sportradar_frontend
    build: ./frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "3000:80"
    networks: 
      - sportradar
      
volumes:
  postgres:
  pgadmin:
  
networks:
  sportradar:
    driver: bridge